### ISSUE TITLE
Aleecers blog

### ISSUE THREAD

**Issue by TheAwiteb** [Aleecers/Aleecers.github.io#1]
After fork [`X7md/x7md.github.io`], we need to customize it to Aleecers blog, there are some important things that need to be modified

- [X] Delete posts
- [X] Delete images
- [X] Update [`favicon.svg`] to Aleecers icon
- [X] Update [`404 image`] to neko
- [X] Update about page
- [X] Update home page
- [X] Remove `portfolio` section
- [X] Update [`README.md`] and mention @x7md in it [[`x7md`]]
- [X] Update [`data.json`]
- [X] Update [`JSONid.js`]
- [X] Update [`astro.config.mjs`]
- [X] Update links
- [X] Update `about-me` section to `about`
- [X] Add more information to rss feed ( image, description )
	- [X] Limit rss feed
	- [X] Add language to rss feed
- [X] Add modified date to blog layout
- [X] Enable comments https://github.com/Aleecers/Aleecers.github.io/commit/aa9ddb4d030b0aeaaeca5ded5d853e9174998bef
- [x] Rust cli to create new post <https://github.com/aleecers/alepc>

[`X7md/x7md.github.io`]: https://github.com/X7md/x7md.github.io
[`x7md`]: https://github.com/X7md
[`README.md`]: https://github.com/Aleecers/Aleecers.github.io/blob/f00b71a4103e45ea8d5968ba7353a32e7af692ac/README.md
[`data.json`]: https://github.com/X7md/x7md.github.io/blob/f00b71a4103e45ea8d5968ba7353a32e7af692ac/src/utility/data.json
[`JSONid.js`]: https://github.com/X7md/x7md.github.io/blob/f00b71a4103e45ea8d5968ba7353a32e7af692ac/src/utility/JSONid.js
[`favicon.svg`]: https://github.com/X7md/x7md.github.io/blob/f00b71a4103e45ea8d5968ba7353a32e7af692ac/public/favicon.svg
[`404 image`]: https://github.com/X7md/x7md.github.io/blob/f00b71a4103e45ea8d5968ba7353a32e7af692ac/public/images/cat.svg
[`astro.config.mjs`]: https://github.com/Aleecers/Aleecers.github.io/blob/f00b71a4103e45ea8d5968ba7353a32e7af692ac/astro.config.mjs#L21

**Comment by X7md** [comment]
Notes:
* data.json was testing for [JSON LD](https://json-ld.org/) FAQ, and it's some sort of structured data [Check This](https://developers.google.com/search/docs/advanced/structured-data/faqpage).
* For more information about what `JSONid.js` does you can read more about it in [this page](https://developers.google.com/search/docs/advanced/structured-data/article), and you can your test your changes [here](https://search.google.com/test/rich-results) to see if it's valid.

Have good luck.

**Comment by X7md** [comment]
> Notes:
> 
> * data.json was testing for [JSON LD](https://json-ld.org/) FAQ, and it's some sort of structured data [Check This](https://developers.google.com/search/docs/advanced/structured-data/faqpage).
> * For more information about what `JSONid.js` does you can read more about it in [this page](https://developers.google.com/search/docs/advanced/structured-data/article), and you can your test your changes [here](https://search.google.com/test/rich-results) to see if it's valid.
> 
> Have good luck.

And other thing, don't forget to change {site: " "}

on astro config file

https://github.com/Aleecers/Aleecers.github.io/blob/f00b71a4103e45ea8d5968ba7353a32e7af692ac/astro.config.mjs#L21

**Comment by TheAwiteb** [comment]
Thank you Hamad ( @X7md ) for the reply, this means a lot to me, I will work on your advice, thanks again
